# Add PR titles, numbers, and contributors to a draft release as they are
# merged. This is the workflow configuration. For the configuration of the
# draft release (labels to use, headings, etc), see .github/release-drafter.yml
# https://github.com/release-drafter/release-drafter
name: Release Drafter

on:
  push:
    # Only run the release drafter on the master branch after a PR is merged
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          # config name to use, relative to .github/
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
